version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: rocker/geospatial:latest
    steps:
      - checkout
      - run: echo "hello world"
      - run: install2.r -e ggalt
      - run: scripts/generate_Rmd.R ggalt
    - store_artifacts:
        path: docs
        destination: artifact-file
