version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: rocker/geospatial:latest
    steps:
      - checkout
      - run:
          name: Install necessary packages
          command: |
          install2.r -e \
            ggalt \
            ggraph
      - run:
          name: Generate Rmds
          command: |
          scripts/generate_Rmd.R --outdir docs\
            ggalt \
            ggraph
      - store_artifacts:
          path: docs
          destination: artifact-file
