version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: rocker/verse:latest
    steps:
      - checkout
      - run: echo "hello world"
      - run: install2.r ggalt
      - run: scripts/generate_Rmd.R ggalt